Homwork 2
================
chenxin zhang cz2634
09/28/2020

## Problem 1

#### Read the Mr.Trashwheel dataset.

``` r
path_to_data = "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx"
```

``` r
trashwhell_df
```

    ## # A tibble: 344 x 14
    ##    dumpster month  year date                weight_tons volume_cubic_ya~
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>            <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31               18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74               13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45               15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06               18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71               13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52               14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76               18
    ## # ... with 334 more rows, and 8 more variables: plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   grocery_bags <dbl>, chip_bags <dbl>, sports_balls <int>,
    ## #   homes_powered <dbl>

#### Read precipitation data for 2018 and 2017.

\*\* 2018

    ## # A tibble: 12 x 3
    ##     year month total
    ##    <dbl> <dbl> <dbl>
    ##  1  2018     1  0.94
    ##  2  2018     2  4.8 
    ##  3  2018     3  2.69
    ##  4  2018     4  4.69
    ##  5  2018     5  9.27
    ##  6  2018     6  4.77
    ##  7  2018     7 10.2 
    ##  8  2018     8  6.45
    ##  9  2018     9 10.5 
    ## 10  2018    10  2.12
    ## 11  2018    11  7.82
    ## 12  2018    12  6.11

\*\* 2017

    ## # A tibble: 12 x 3
    ##     year month total
    ##    <dbl> <dbl> <dbl>
    ##  1  2017     1  2.34
    ##  2  2017     2  1.46
    ##  3  2017     3  3.57
    ##  4  2017     4  3.99
    ##  5  2017     5  5.64
    ##  6  2017     6  1.4 
    ##  7  2017     7  7.09
    ##  8  2017     8  4.44
    ##  9  2017     9  1.95
    ## 10  2017    10  0   
    ## 11  2017    11  0.11
    ## 12  2017    12  0.94

``` r
# create a data frame for month
month_df = 
  tibble(
    month = 1:12, 
    month_name = month.name
  )
```

``` r
# row-combine precip_2018 and precip_2017
precip_df = 
  bind_rows(precip_2018, precip_2017) 
precip_m = left_join(precip_df, month_df, by = "month") 
precip_m 
```

    ## # A tibble: 24 x 4
    ##     year month total month_name
    ##    <dbl> <dbl> <dbl> <chr>     
    ##  1  2018     1  0.94 January   
    ##  2  2018     2  4.8  February  
    ##  3  2018     3  2.69 March     
    ##  4  2018     4  4.69 April     
    ##  5  2018     5  9.27 May       
    ##  6  2018     6  4.77 June      
    ##  7  2018     7 10.2  July      
    ##  8  2018     8  6.45 August    
    ##  9  2018     9 10.5  September 
    ## 10  2018    10  2.12 October   
    ## # ... with 14 more rows

This dataset contains information from the Mr.Trashwheel trash collector
in Baltimore, Maryland. As trash enters the inner harbor, the trashwheel
collects that trash, and stores it in a dumpster. The dataset contains
information on year, month, and trash collected, include some specific
kinds of trash. There are a total of 344 rows in our final dataset.
Additional data sheets include monthly precipitation for year 2017 and
2018. The total monthly precipitation for year 2017 is 32.93 (in). The
total monthly precipitation for year 2018 is 70.33 (in).

## Problem 2

#### Read and Clean the NYC Transit dataset

``` r
transit_df = 
  read_csv(
    "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names() %>%  # transfer to lowercase
  select(line:entry, vending, ada) %>% #keep specific columns
  mutate(entry = recode(entry, "Yes" = "True", "No" = "False"),
         entry = as.logical(entry)) # change 'entry' from charactor variable to logical variable
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_double(),
    ##   Route9 = col_double(),
    ##   Route10 = col_double(),
    ##   Route11 = col_double(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

``` r
transit_df
```

    ## # A tibble: 1,868 x 19
    ##    line  station_name station_latitude station_longitu~ route1 route2 route3
    ##    <chr> <chr>                   <dbl>            <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Av~ 25th St                  40.7            -74.0 R      <NA>   <NA>  
    ##  2 4 Av~ 25th St                  40.7            -74.0 R      <NA>   <NA>  
    ##  3 4 Av~ 36th St                  40.7            -74.0 N      R      <NA>  
    ##  4 4 Av~ 36th St                  40.7            -74.0 N      R      <NA>  
    ##  5 4 Av~ 36th St                  40.7            -74.0 N      R      <NA>  
    ##  6 4 Av~ 45th St                  40.6            -74.0 R      <NA>   <NA>  
    ##  7 4 Av~ 45th St                  40.6            -74.0 R      <NA>   <NA>  
    ##  8 4 Av~ 45th St                  40.6            -74.0 R      <NA>   <NA>  
    ##  9 4 Av~ 45th St                  40.6            -74.0 R      <NA>   <NA>  
    ## 10 4 Av~ 53rd St                  40.6            -74.0 R      <NA>   <NA>  
    ## # ... with 1,858 more rows, and 12 more variables: route4 <chr>, route5 <chr>,
    ## #   route6 <chr>, route7 <chr>, route8 <dbl>, route9 <dbl>, route10 <dbl>,
    ## #   route11 <dbl>, entrance_type <chr>, entry <lgl>, vending <chr>, ada <lgl>

The dataset is consist of 1868 obervations and 19 varaibles. The
variables include line, station\_name, station\_latitude,
station\_longitude, route1, route2, route3, route4, route5, route6,
route7, route8, route9, route10, route11, entrance\_type, entry,
vending, ada. Some works I did so far include:  
\* clean the varaible names to lowercase, \* choose columns that we are
interested in, \* recode a character varaible(entry) to a logical
varaible.

The NYC transits dataset includes 465 distinct stations. Among these
stations, 84 stations are ADA compliant. The proportion of station
entrances/exits without vending allow entrance is 9.7965739%.

#### Reformat data so that route number and route name are distinct variables.

``` r
transit_tidy = 
  transit_df %>% 
  mutate_at(vars(route1:route11), as.character) %>% # convert number to character
  pivot_longer(
    route1:route11,
    names_to = "route_name",
    values_to = "route_number") %>% 
  drop_na(route_number)
```

  - The transit dataset shows there are 60 stations serve the A train.
  - Of the stations that serve the A train, 17 are ADA compliant.
